version: '3.8'

services:
  # Neo4j Database with Graph Data Science - AMD64 Optimized
  neo4j:
    image: neo4j:5.15-enterprise
    platform: linux/amd64
    container_name: tradie-neo4j-amd64
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/tradiemate123
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial_size=1G
      - NEO4J_dbms_memory_heap_max_size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j_data_amd64:/data
      - neo4j_logs_amd64:/logs
      - neo4j_import_amd64:/var/lib/neo4j/import
      - neo4j_plugins_amd64:/plugins
    networks:
      - tradie-network-amd64
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p tradiemate123 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # CrewAI FastAPI Backend - AMD64 Optimized
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: tradie-backend-amd64
    ports:
      - "10000:10000"
    environment:
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=tradiemate123
      - PORT=10000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:12001
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - tradie-network-amd64
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Supabase for Frontend Data Storage - AMD64 Optimized
  supabase-db:
    image: supabase/postgres:15.1.0.147
    platform: linux/amd64
    container_name: tradie-supabase-db-amd64
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=your-super-secret-and-long-postgres-password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - supabase_db_data_amd64:/var/lib/postgresql/data
    networks:
      - tradie-network-amd64
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # Supabase API - AMD64 Optimized
  supabase-api:
    image: supabase/gotrue:v2.132.3
    platform: linux/amd64
    container_name: tradie-supabase-api-amd64
    ports:
      - "54321:8000"
    environment:
      - GOTRUE_API_HOST=0.0.0.0
      - GOTRUE_API_PORT=8000
      - GOTRUE_DB_DRIVER=postgres
      - GOTRUE_DB_DATABASE_URL=postgres://supabase_auth_admin:root@supabase-db:5432/postgres
      - GOTRUE_SITE_URL=http://localhost:3000
      - GOTRUE_URI_ALLOW_LIST=http://localhost:3000
      - GOTRUE_JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long
      - GOTRUE_JWT_EXP=3600
      - GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
      - GOTRUE_JWT_ADMIN_ROLES=service_role
      - GOTRUE_JWT_AUD=authenticated
    depends_on:
      supabase-db:
        condition: service_healthy
    networks:
      - tradie-network-amd64

  # Next.js Frontend - AMD64 Optimized
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: tradie-frontend-amd64
    ports:
      - "12001:3000"
    environment:
      - NODE_ENV=production
      - CREWAI_BACKEND_URL=http://backend:10000
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - NEXT_PUBLIC_APP_NAME=TradieMate Marketing Analytics
      - NEXT_PUBLIC_APP_DESCRIPTION=AI-powered Google Ads and website optimization for trade businesses
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
      supabase-api:
        condition: service_started
    networks:
      - tradie-network-amd64
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

volumes:
  neo4j_data_amd64:
  neo4j_logs_amd64:
  neo4j_import_amd64:
  neo4j_plugins_amd64:
  supabase_db_data_amd64:

networks:
  tradie-network-amd64:
    driver: bridge